### ISSUE TITLE
NullReferenceException while getting containers

### ISSUE THREAD

**Issue by kroshner** [mariotoffia/FluentDocker#46] opened 2018-06-13 13:52 UTC
Sometimes I get `NullReferenceException` while getting list of all containers via `IHostService.GetContainers()`

The problem is that `Host.InspectContainer(id, Certificates).Data` returns null for some reason. However `Host.InspectContainer(id, Certificates).Success` returns `true` at the same time.

Any ideas what could be wrong?
Thanks in advance

**Comment by mariotoffia** [comment] 2018-06-14 14:54
Do you get the containers while delete containers from other thread or process?
Since I have no way of verifying this, I've added check on the exit code and therefore it sould (in theory) give you the stderr of the command - If so I would like to have the error log to diagnose the problem.

Cheers,
 Mario

**Comment by kroshner** [comment] 2018-06-14 19:35
My setup is Gitlab Runner (docker executor) Job (docker-compose image) which builds docker image with my applications. This built image is responsible for running my applications via `docker-compose up`. I use this setup for testing interaction between my applications, so I run this setup per each Test Fixture. My unit tests framework is nUnit v3. From the test running logs I would say that I `shouldn't` have any code working on `compose up` | `compose down` in parallel.

**Comment by kroshner** [comment] 2018-06-14 19:36
What I've done so far - created a `Polly` `RetryPolicy` to handle exceptions while getting containers via `IHostService.GetContainers()`

**Comment by mariotoffia** [comment] 2018-06-15 05:44
What I will do is to make it more error resilient - however it would be nice if you could get a error log (if such is available) with the new nuget package. From a software point of view it is quite possible that a container is not present when doing inspect after a ```docker ps``` and thus I'll just discard such container. But it doesn't feel right until one can reproduce the problem.

**Comment by mariotoffia** [comment] 2018-06-15 06:02
I've already committed a fix that makes ```GetContainers``` handle the situation correctly (i.e. no NPE) but I do really, if you have the possibility, to get to know what _exactly_ happening on you docker daemon side. Is it containers that do not exists when doing inspect or...

**Comment by mariotoffia** [comment] 2018-06-15 06:06
the above is pushed to nuget as _2.2.17_. Can you please tell me when you have tried 2.2.17 if it solved your problem or not?

**Closed** 2018-06-24 19:45 UTC
Labels: bug
